-- Database Schema for MySQL

-- 1. Create Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    short_description TEXT NOT NULL,
    description TEXT NOT NULL,
    tech_stack VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    badges VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Create Admin Users Table
CREATE TABLE IF NOT EXISTS admin_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Seed with real portfolio projects from cyrylbitangcol.com/portfolio/
INSERT INTO projects (title, short_description, description, tech_stack, image_url, link, category, badges) VALUES
('Hongkong Tech Match', 'A modern, responsive platform connecting businesses with top tech solutions in Kowloon, Hong Kong.', 'Explore the Hongkong Tech Match website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A modern, responsive platform connecting businesses with top tech solutions in Kowloon, Hong Kong.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Hongkong-Tech-Match-scaled.png', 'https://cyrylbitangcol.com/portfolio/hongkong-tech-match/', 'figma web-design', 'Figma, Elementor, Web Design'),
('Tea Dreamer', 'A stylish, responsive platform showcasing premium tea blends and products in Tuen Mun Central Post Office, Hong Kong.', 'Discover the Tea Dreamer website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A stylish, responsive platform showcasing premium tea blends and products in Tuen Mun Central Post Office, Hong Kong.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Tea-Dreamer-scaled.png', 'https://cyrylbitangcol.com/portfolio/tea-dreamer/', 'figma web-design', 'Figma, Elementor, Web Design'),
('JRA Construction', 'A responsive platform showcasing construction services and projects in Auckland, New Zealand.', 'Visit the JRA Construction website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A responsive platform showcasing construction services and projects in Auckland, New Zealand.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/JRA-Construction-scaled.png', 'https://cyrylbitangcol.com/portfolio/jra-construction/', 'figma web-design web-development', 'Figma, Elementor, Web Dev'),
('Prisma Digital', 'A modern, responsive platform showcasing digital marketing and technology services.', 'Explore the Prisma Digital website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A modern, responsive platform showcasing digital marketing and technology services.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Prisma-Digital-scaled.png', 'https://cyrylbitangcol.com/portfolio/prisma-digital/', 'figma web-design web-development', 'Figma, Elementor, Web Dev'),
('Joy Med Clinic', 'A modern, responsive platform showcasing healthcare services in Tsim Sha Tsui, Hong Kong.', 'Visit the Joy Med Clinic website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A modern, responsive platform showcasing healthcare services in Tsim Sha Tsui, Hong Kong.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Joy-Med-Clinic-scaled.png', 'https://cyrylbitangcol.com/portfolio/joy-med-clinic/', 'figma web-design', 'Figma, Elementor, Web Design'),
('MC Ceci Wu', 'A sophisticated, responsive platform showcasing event hosting services in Causeway Bay, Hong Kong.', 'Explore the MC Ceci Wu website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A sophisticated, responsive platform showcasing event hosting services in Causeway Bay, Hong Kong.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/MC-Ceci-Wu-scaled.png', 'https://cyrylbitangcol.com/portfolio/mc-ceci-wu/', 'figma web-design', 'Figma, Elementor, Web Design'),
('Beze Club', 'A stylish, responsive platform showcasing membership and services in Tai Yau St, Hong Kong.', 'Discover the Beze Club website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A stylish, responsive platform showcasing membership and services in Tai Yau St, Hong Kong.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Beze-Club-scaled.png', 'https://cyrylbitangcol.com/portfolio/beze-club/', 'figma web-design', 'Figma, Elementor, Web Design'),
('Skills Training Center', 'A responsive platform highlighting training programs and educational services in Ontario, CA.', 'Visit the Skills Training Center website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A responsive platform highlighting training programs and educational services in Ontario, CA.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Skills-Training-Center-scaled.png', 'https://cyrylbitangcol.com/portfolio/skills-training-center/', 'web-design web-development', 'Figma, Elementor, Web Dev'),
('Nextminds Web Solutions', 'A clean, responsive platform showcasing digital services in Ontario, CA.', 'Explore the Nextminds Web Solutions website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A clean, responsive platform showcasing digital services in Ontario, CA.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Nextminds-Web-Solutions-scaled.png', 'https://cyrylbitangcol.com/portfolio/nextminds-web-solutions/', 'web-design web-development', 'Figma, Elementor, Web Dev'),
('UPCA Real Estate Marketing & Media', 'A sleek, responsive platform showcasing real estate listings and services in Ontario, CA.', 'Discover the UPCA Real Estate website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A sleek, responsive platform showcasing real estate listings and services in Ontario, CA.', 'WordPress, Elementor Pro, Figma', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/UPCA-Real-Estate-scaled.png', 'https://cyrylbitangcol.com/portfolio/upca-real-estate-marketing-media/', 'figma web-design web-development', 'Figma, Elementor, Web Dev'),
('Hongkong Relocations', 'A sleek, responsive platform offering trusted moving services in Kwun Tong, HK.', 'Explore the Hongkong Relocations website, designed by Cyryl Bitangcol using Elementor Pro and Figma. A sleek, responsive platform offering trusted moving services in Kwun Tong, HK.', 'WordPress, Elementor Pro, Figma, WooCommerce', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Hongkong-Relocations-scaled.png', 'https://cyrylbitangcol.com/portfolio/hongkong-relocations/', 'ecommerce figma web-design web-development', 'E-Commerce, Figma, Elementor'),
('Module Interior Design', 'A sleek, responsive platform for interior design services in Kowloon, HK.', 'Explore the Module Interior Design website designed by Cyryl Bitangcol using Elementor Pro and Figma. A sleek, responsive platform for interior design services in Kowloon, HK.', 'WordPress, Elementor Pro, Figma, WooCommerce', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Module-Interior-Design-scaled.png', 'https://cyrylbitangcol.com/portfolio/module-interior-design/', 'ecommerce figma web-design web-development', 'E-Commerce, Figma, Elementor'),
('Aurumara', 'A responsive, elegant eCommerce platform for a premium shopping experience.', 'Discover the Aurumara online store, designed by Cyryl Bitangcol using Elementor Pro and Figma. A responsive, elegant eCommerce platform for a premium shopping experience.', 'WordPress, Elementor Pro, Figma, WooCommerce', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Aurumara-scaled.png', 'https://cyrylbitangcol.com/portfolio/aurumara/', 'ecommerce figma web-design web-development', 'E-Commerce, Figma, Elementor'),
('Supkid Market', 'A user-friendly, responsive online store for customers in Sheung Wan, Hong Kong.', 'Explore the Supkid Market website designed by Cyryl Bitangcol using Elementor Pro and Figma. A user-friendly, responsive online store for customers in Sheung Wan, Hong Kong.', 'WordPress, Elementor Pro, Figma, WooCommerce', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Supkid-Market-scaled.png', 'https://cyrylbitangcol.com/portfolio/supkid-market/', 'ecommerce figma web-design web-development', 'E-Commerce, Figma, Elementor'),
('Shawn Tiberio', 'A custom, responsive, and visually captivating online experience built with Divi Theme and Photoshop.', 'Explore the Shawn Tiberio website designed by Cyryl Bitangcol, utilizing Divi Theme and Photoshop for a custom, responsive, and visually captivating online experience.', 'WordPress, Divi Theme, Photoshop', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Shawn-Tiberio-scaled.png', 'https://cyrylbitangcol.com/portfolio/shawn-tiberio/', 'web-design web-development', 'Divi, Web Dev'),
('Offer Charm', 'A responsive platform offering exclusive deals and discounts for users in Orlando, FL.', 'Explore the Offer Charm website, designed by Cyryl Bitangcol using Divi Theme and Photoshop. A responsive platform offering exclusive deals and discounts for users in Orlando, FL.', 'WordPress, Divi Theme, Photoshop', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Offer-Charm-scaled.png', 'https://cyrylbitangcol.com/portfolio/offer-charm/', 'web-design web-development', 'Divi, Web Dev'),
('Grandma Scones', 'A responsive, visually stunning online store for scone lovers in Tsim Sha Tsui, HK.', 'Explore the Grandma Scones website designed by Cyryl Bitangcol using Elementor Pro, Figma, and Photoshop. A responsive, visually stunning online store for scone lovers in Tsim Sha Tsui, HK.', 'WordPress, Elementor Pro, Figma, Photoshop, WooCommerce', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Grandma-Scones-scaled.png', 'https://cyrylbitangcol.com/portfolio/grandma-scones/', 'web-design web-development', 'Figma, Elementor, Web Dev'),
('Blue Halo Homes', 'Experience a luxurious, responsive site that showcases exceptional craftsmanship.', 'Discover the Blue Halo Homes website, designed by Cyryl Bitangcol using Divi Theme and Photoshop. Experience a luxurious, responsive site that showcases exceptional craftsmanship.', 'WordPress, Divi Theme, Photoshop', 'https://cyrylbitangcol.com/wp-content/uploads/2020/09/Blue-Halo-scaled.png', 'https://cyrylbitangcol.com/portfolio/blue-halo-homes/', 'web-design web-development', 'Divi, Web Dev');
